version: '3'

services:
  db:
    image: 'postgres:15'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: mezink_golang_assignment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mezink
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 10s
    networks:
      - test
  app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - test
networks:
  test:
